/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "qtgusfvncorjcxcayofg"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0Z3VzZnZuY29yamN4Y2F5b2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NTI1MjUsImV4cCI6MjA3NzEyODUyNX0.yoH0J69cMjxOtxnXV1BarYzyA5hZbmuZ_2boWUV1SE4"